# -*- coding: utf-8 -*-
"""Lab08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AiDGrXoGy5K8MTn7HgdEaNG93ruNevo7
"""

# y =w3x3 +w2x2 +x1x1 +w0
import numpy as np
A = np.array([[60,5.5,1,1],[65,5,0,1],[55,6,1,1],[50,5,1,1]])
b = np.array([66,74,78,72])
w = (np.linalg.inv(A.T@A)@A.T)@b.T
print(w)
weight = 60
height = 5
sm = 1
year_old = w[0] *weight + w[1]*height + w[2]*sm +w[3]
print(year_old)

########### ex1
A = np.array([[2,2],[2,3]])
b = np.array([4,6])
x = (np.linalg.inv(A.T@A)@A.T)@b.T
print(x)

#ex2
A = np.array([[0,0,1],[0,1,1],[1,2,1],[1,0,1],[4,1,1],[4,2,1]])
b = np.array([0.5,1.6,2.8,0.8,5.1,5.9])
x = (np.linalg.inv(A.T@A)@A.T)@b.T
print(x)

#ex3

def check (A,b):
  x = (np.linalg.inv(A.T@A)@A.T)@b.T
  print(x)

A1 = np.array([[1,0],[1,1],[1,2],[1,3]])
b1 = np.array([1,1,2,2])
check(A1,b1)

A2 = np.array([[1,1],[1,2],[1,4],[1,5]])
b2 = np.array([0,1,2,3])
check(A2,b2)

A3 = np.array([[1,-1],[1,0],[1,1],[1,2]])
b3 = np.array([0,1,2,4])
check(A3,b3)

A4 = np.array([[1,2],[1,3],[1,5],[1,6]])
b4 = np.array([3,2,1,0])
check(A4,b4)

#ex4
# ax +b 
# x = np.array([2000,6000,20000,30000,40000])
b = np.array([20,18,10,6,2])
A = np.array([[2000,1],[6000,1],[20000,1],[30000,1],[40000,1]])
x = (np.linalg.inv(A.T@A)@A.T)@b.T
print(x)

#ex5
import math 

A = np.array([[math.cos(1),math.sin(1)],[math.cos(2),math.sin(2)],[math.cos(3),math.sin(3)]])
B = np.array([7.9,5.4,-9])
x = (np.linalg.inv(A.T@A)@A.T)@B.T
print(x)

#ex6
# ax^3 +bx^2 +cx +d
import matplotlib.pyplot as plt
x = np.array([1,2,3,4,5,6])
y = np.array([2.1,3.5,4.2,3.1,4.4,6.8])

A = np.array([[1,1,1,1],[8,4,2,1],[27,9,3,1],[4**3,4**2,4,1],[5**3,5**2,5,1],[6**3,6**2,6,1]])
B = np.array([2.1,3.5,4.2,3.1,4.4,6.8])
w = (np.linalg.inv(A.T@A)@A.T)@B.T
print(w)
y_hat = w[0]*A[:,0] + w[1]
plt.plot(A[:,0],B,'ro')

plt.plot(A[:,0],y_hat,'ro')
plt.plot(A[:,0],y_hat,'b')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

A = np.array([[1400,1],
              [1600,1],[1700,1],
              [1875,1],[1100,1],
              [1550,1],[2350,1],
              [2450,1],[1425,1],
              [1700,1]])
b = np.array([245,312,279,308,199,219,405,324,319,255])
w = (np.linalg.inv(A.T@A)@A.T)@b.T
print(w)

square_feet = 1200
y_pred = w[0]*square_feet +w[1]
print(y_pred)

y_hat = w[0]*A[:,0] + w[1]
fig = plt.figure()
plt.plot(A[:,0],b,'ro')
plt.plot(A[:,0],y_hat,'ro')
plt.plot(A[:,0],y_hat,'b')
plt.show()

mse = 0.0
for i in range(A.shape[0]):
  mse += (b[i]-y_hat[i])**2
mse = mse / A.shape[0]
print(mse)